### ISSUE TITLE
Visually appealing design

### ISSUE THREAD

**Issue by JOCPhys** [Gerbil1511/Science-Shuffle#13]
As a teacher I want the design to be visually appealing and engaging so that it attracts and retains students' interest

**Acceptance Criteria:**

- [x] The game should use vibrant, educational-themed graphics and animations.
- [x] The user interface (UI) should be consistent and visually appealing.
- [x] Visual cues and effects should enhance the gameplay experience without being distracting.

Tasks:

- [x] Design and implement graphics and animations that are relevant to the educational content.
- [x] Ensure a consistent design language across the entire game.
- [x] Use css and javascript to flip cards

**Comment by jjyutm4532** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the CSS to include vibrant colors, animations, and consistent styling to make the game more visually appealing and engaging for students.

You can review changes in this commit: https://github.com/jjyutm4532/Gerbil1511-Science-Shuffle-13/commit/8b9fe72a8b94b463b9bccd7f0d7ccd66bf2f246e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
